spring.application.name=rest-api

# Configuración del Datasource
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.sswdufqbqxxcyrsopoik
spring.datasource.password=spq2526_eng
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Supabase Auth
supabase.url=https://sswdufqbqxxcyrsopoik.supabase.co
supabase.anon-key=sb_publishable_3lBQYpuGNUlDk7aq597o6g_bk_deh3p
supabase.service-role-key=sb_secret_0uxtgBq6OUGrlkAyCcJX-w_mBlsEwgv

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
