create table if not exists public."user" (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default timezone('utc', now()),
    username text unique,
    phone text,
    email text,
    password text
);