-- Drop old user table and all dependent FK constraints
drop table if exists public."user" cascade;

-- Create profiles table linked to Supabase Auth
create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    username text unique not null,
    phone text,
    created_at timestamptz not null default timezone('utc', now())
);

-- Migrate FK columns from bigint to uuid and re-link to profiles
-- list.seller_id
alter table if exists public.list
    drop column if exists seller_id,
    add column seller_id uuid references public.profiles(id) on delete set null;

-- payment.buyer
alter table if exists public.payment
    drop column if exists buyer,
    add column buyer uuid references public.profiles(id) on delete set null;

-- post.author
alter table if exists public.post
    drop column if exists author,
    add column author uuid references public.profiles(id) on delete set null;

-- Add admin flag to profiles
alter table public.profiles
    add column if not exists is_admin boolean not null default false;

create table if not exists public.reviews (
    id bigint generated by default as identity primary key,
    item_id bigint not null references public.items(id) on delete cascade,
    author_id uuid not null references public.profiles(id) on delete cascade,
    rating integer not null check (rating between 1 and 5),
    comment text,
    created_at timestamptz not null default timezone('utc', now())
);
